export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const DELETE_ITEMS = 'DELETE_ITEMS'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const UPDATE_ITEMS = 'UPDATE_ITEMS'


//request
export const GET_POST_PENDING = 'GET_POST_PENDING'
export const GET_POST_FULFILLED = 'GET_POST_FULFILLED'
export const GET_POST_REJECTED = 'GET_POST_REJECTED'
